<?php 
//echo md5("123456");
echo $this->partial('_partials/_messages.phtml', array('flashMessages' => $this->flashMessages)); ?>
<div id="contentLoginMLS">
    <center><h6 class="TitleLoginEs">Ingrese al Cuestionario</h6></center>
    <form id="loginMLS" method="post" action="">
        <fieldset class="blockFieldMLS">
            <div class="bloqueL">
                <label for="usuarioMLS" class="textoLogin left fnormal">Usuario</label>
                <?php $errors = $this->frmlogin->userEmail->hasErrors(); ?>
                <?= $this->frmlogin->userEmail->setAttribs(array('alt' => '', 'id' => 'femail', 'class' => 'sizeInputLogin placeH cGray left', 'tabindex' => '1'))->renderViewHelper(); ?>
                <span class="responseLog left <?php echo ($errors)?'bad':'' ?>">
                    <?php echo ($errors?$this->frmlogin->userEmail->errMsg:''); ?>
                </span>
            </div>
            <div class="respW"></div>
            <div class="bloqueL">
                <label for="passMLS" class="textoLogin left fnormal">Contraseña</label>
                <?php $errors = $this->frmlogin->userPass->hasErrors(); ?>
                <?= $this->frmlogin->userPass->setAttribs(array('id' => 'fpassword', 'class' => 'sizeInputLogin left', 'tabindex' => '1'))->renderViewHelper(); ?>
                <span class="responseLog left <?php echo ($errors)?'bad':'' ?>">
                    <?php echo ($errors?$this->frmlogin->userPass->errMsg:''); ?>
                </span>
            </div>
            <div class="btnContent">
                <input type="submit" id="" value="Ingresar" class="button left"/>
            </div>
            <div class="respW"></div>
        </fieldset>
        <?= $this->frmlogin->return->renderViewHelper(); ?>
        <?= $this->frmlogin->tipo->renderViewHelper(); ?>
        <?= $this->frmlogin->auth_token->renderViewHelper(); ?>
    </form>
</div>