<?php echo $this->partial('_partials/_messages.phtml', array('flashMessages' => $this->flashMessages)); ?>
<?php echo $this->partial('_partials/_menu.phtml', array('activo'=>$this->activo)); ?>
<?php 
$res = new Application_Model_Pregunta();
?>
<style>
    
 .normal:hover{background: #FFFFC1; }
 .btn-group .btn:last-child, .btn-group .dropdown-toggle {
    border-bottom-right-radius: 4px;
    border-top-right-radius: 4px;
}

/*
tr.encuesta:nth-child(even) {background: #CCC }
tr.encuesta:nth-child(odd) {background: #FFF}

tr.class:nth-child(even) {background: #EEE}
tr.class:nth-child(odd) {background: #FFF}
*/
.btn-group .btn {
    border-radius: 0 0 0 0;
    float: left;
    margin-left: -1px;
    position: relative;
}
.btn {
    -moz-border-bottom-colors: none;
    -moz-border-image: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background-color: #F5F5F5;
    background-image: -moz-linear-gradient(center top , #FFFFFF, #E6E6E6);
    background-repeat: repeat-x;
    border-color: #CCCCCC #CCCCCC #B3B3B3;
    border-radius: 4px 4px 4px 4px;
    border-style: solid;
    border-width: 1px;
    box-shadow: 0 1px 0 rgba(255, 255, 255, 0.2) inset, 0 1px 2px rgba(0, 0, 0, 0.05);
    color: #333333;
    cursor: pointer;
    display: inline-block;
    font-size: 13px;
    line-height: 18px;
    margin-bottom: 0;
    padding: 4px 10px;
    text-align: center;
    text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75);
    vertical-align: middle;
}
a {
    color: #0088CC;
    text-decoration: none;
}
.btn.disabled, .btn[disabled] {
    background-color: #E6E6E6;
    background-image: none;
    box-shadow: none;
    cursor: default;
    opacity: 0.65;
}
#infopaginas {
    float: right;
    padding: 7px 14px 0 0;
}
</style>


<div class="">

    <form action="/cuestionario/agregar" method="post" name="frmcuestionario" id="frmcuestionario">
        
      <div style="padding: 20px">
            

        <table width="1000" border="0" align="center" cellpadding="5" cellspacing="0">
             
             <tr>
               <td colspan="3"><div align="center"><strong>INSTRUCCIONES</strong></div></td>
             </tr>
             <tr>
               <td colspan="3">&nbsp;</td>
          </tr>
             <tr>
               <td colspan="3" bgcolor="#E9E9E9"><?=$this->paginationControl($this->listaPreguntas, 'Sliding', 'pagination.phtml', array('generar' => true)); ?></td>
             </tr>
             <tr>
               <td colspan="3"><p>
                      
                       Este  cuestionario contiene un conjunto de frases que cortas que permite hacer una  descripción de Ud. mismo(a). </p>
               <p>Para ello,  diga en qué medida cada una de las oraciones que aparecen a continuación es  verdadera, de acuerdo a como te sientes, piensas o actúas la mayoría de veces,  poniendo una X sobre el número que mejor exprese la respuesta que Ud. Indique. </p>
               <table width="100%" border="0" cellpadding="2" cellspacing="2">
                 <tr>
                   <td><p>Hay seis  respuestas posibles  por cada frase.</p></td>
                 </tr>
                 <tr>
                   <td><table width="80%" border="0" align="center" cellpadding="0" cellspacing="0">
                     <tr>
                       <td>
                       <table  border="0" align="center">
                 <tr>
                   <th style="width:90px">Raras Veces</th>
                   <th style="width:90px">Pocas Veces</th>
                   <th style="width:90px">Algunas veces</th>
                   <th style="width:90px">Muchas veces</th>
                   <th style="width:90px">Frecuente-mente</th>
                   <th style="width:90px">Siempre</th>
                 </tr>
               </table>
                       </td>
                     </tr>
                     <tr>
                       <td><table  border="0" align="center">
                         <tr style="height:30px;">
                           <th bgcolor="#E0E0E0" style="width:90px">1</th>
                           <th bgcolor="#E0E0E0" style="width:90px">2</th>
                           <th bgcolor="#E0E0E0" style="width:90px">3</th>
                           <th bgcolor="#E0E0E0" style="width:90px">4</th>
                           <th bgcolor="#E0E0E0" style="width:90px">5</th>
                           <th bgcolor="#E0E0E0" style="width:90px">6</th>
                         </tr>
                       </table></td>
                     </tr>
                   </table></td>
                 </tr>
                 <tr>
                   <td><p><em><u>No piense demasiado en las frases, ni  emplee mucho tiempo en decidirse.</u></em></p></td>
                 </tr>
               </table>
               <p>&nbsp;</p></td>
          </tr>
          <tr id="contentEnc">
               <td>&nbsp;</td>
               <td>&nbsp;</td>
               <td>
               <div align="right">
               <table  border="0">
                 <tr>
                   <th bgcolor="#CCCCCC" style="width:77px">Raras Veces</th>
                   <th bgcolor="#CCCCCC" style="width:77px">Pocas Veces</th>
                   <th bgcolor="#CCCCCC" style="width:77px">Algunas veces</th>
                   <th bgcolor="#CCCCCC" style="width:77px">Muchas veces</th>
                   <th bgcolor="#CCCCCC" style="width:77px">Frecuente - mente</th>
                   <th bgcolor="#CCCCCC" style="width:77px">Siempre</th>
                 </tr>
               </table>
               </div>
               </td>
          </tr>
          <tr >
            <td colspan="3">
            
              <table width="100%" border="0" id="encuesta">
                <?php  
              $i=0;
              foreach($this->listaPreguntas as $index=>$item){ $i++;?>
         
         <?php //echo ($i%2==0?'style="background: #FFF"':'') ?>
          
          <tr   class="normal encuesta">
            <td width="2%">&nbsp;<?php echo $item['id'];?></td>
            <td width="49%">&nbsp;<?php echo $item['descrip'];?></td>
            <td width="49%">
              
                 <?php if (count($item['opcion'])>0 ) {?>
                  <div align="right">
              <table  border="0">
                  <tr >
                  <?php  foreach($item['opcion'] as $key=>$value){
                          //$seect = $this->asdasd(1);
                      ?>
                <th style="width:90px">
                    <?php $op = $res->getRespuesta($item['id']);  ?>
                    <input type="radio" value="<?php echo $value['id'];?>" title="<?php echo $value['name'];?>" name="<?php echo $item['id']?>" id="<?php echo $item['id'];?>" <?php echo ($value['id']==$op)?'checked="cheked"':''  ?> >
                </th>
                <?php } ?>
                
              </tr>
            </table>
            </div>
                <?php } ?>
                
            </td>
          </tr>
          
          <?php } ?>
            </table></td>
          </tr>    
             
          
          
          <tr>
            <td colspan="3">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="3">
            <div style="padding:3px" align="center">
            <input type="submit" name="button" id="button" value="Guardar Cambios" />
            </div>
            </td>
          </tr>
          <tr>
            <td colspan="3" bgcolor="#E9E9E9"><?=$this->paginationControl($this->listaPreguntas, 'Sliding', 'pagination.phtml', array('generar' => true)); ?></td>
          </tr>
          
        </table>
       
           </div>
    </form>

</div>